version: '0.0.1.{build}'
before_build:
  - nuget restore
artifacts:
  - path: Messier16.Forms.Controls.$(APPVEYOR_BUILD_VERSION).nupkg
    name: nuget_pack
after_build:
  - nuget pack "C:\projects\forms-controls\Messier16.Forms.Controls.nuspec" -Properties "Configuration=Debug;Platform=AnyCPU" -IncludeReferencedProjects
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Messier16.Forms.Controls.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
#deploy:
#  provider: NuGet
#  api_key:
#    secure: XImXaAhmv7juP3N1QLgjU+V2u1+QjEXJnj3mv3U1uCjSzOa8c+LTl2KP3s/ClxhJ
#  artifact: /.*\.nupkg/
#  on:
#    branch: master